language: minimal
  
services:
  - docker

os: linux

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)
    - IMAGE_NAME=roku-remote-rest-server
    - REPO_NAME=jnk5y/$IMAGE_NAME
    - TARGET_PLATFORMS=linux/amd64
  
before_install:
  - docker build -t $REPO_NAME:$TRAVIS_COMMIT_SHORT -t $REPO_NAME:latest .
  
script:  
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push $REPO_NAME:$TRAVIS_COMMIT_SHORT
  - docker push $REPO_NAME:latest
