version: "3.7"

secrets:
  AUTHKEY:
    external: true

services:
  app:
    image: jnk5y/roku-remote-rest-server
    deploy:
      replicas: 1
    secrets:
      - AUTHKEY
    ports:
      - "8889:8889/tcp"
    environment:
      TZ: 'US/Eastern'
      CERTPATH: 'your/cert/path/'
    volumes:
      - '/etc/letsencrypt/:/usr/src/app/certs/:z'
    healthcheck:
      test: curl --fail -k -s https://localhost:8889/roku/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 2
    restart: unless-stopped
