version: "3.7"

secrets:
  AUTHKEY:
    external: true

services:
  app:
    image: jnk5y/roku-remote-rest-server
    deploy:
      replicas: 1
    secrets:
      - AUTHKEY
    ports:
      - "8889:8889/tcp"
    environment:
      TZ: 'US/Eastern'
      CERTPATH: 'live/server.kyrus.xyz/'
      HEALTHCHECK_URL: 'https://server.kyrus.xyz:8889/roku/health'
    volumes:
      - '/etc/letsencrypt/:/usr/src/app/certs/:z'
    healthcheck:
      test: python3 /usr/src/app/healthcheck.py
      interval: 1m
      timeout: 10s
      retries: 2
    restart: unless-stopped
